### ISSUE TITLE
Generated images seem to be broken

### ISSUE THREAD

**Issue by hugomrdias** [filecoin-project/specs#1213]
https://spec.filecoin.io/#systems__filecoin_markets

Possibly related to fleek or internal mess up.

reported by @pooja

**Comment by hugomrdias** [comment]
@andyschwab this seems to be related to fleek, mermaid diagrams pipeline is probably failing in the build.

**Comment by andyschwab** [comment]
Logs from most recent Fleek build: 


6:09:26 AM 10/15/2020: Deploy started
6:09:28 AM 10/15/2020: Docker image: 'fleek/hugo'
6:09:28 AM 10/15/2020: Build command: 'npm install; npm run build'
6:09:28 AM 10/15/2020: Triggering build execution...
6:10:27 AM 10/15/2020: npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
6:10:27 AM 10/15/2020: npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
6:10:29 AM 10/15/2020: npm WARN deprecated har-validator@5.1.5: this library is no longer supported
6:10:44 AM 10/15/2020: > puppeteer@5.3.1 install /workspace/node_modules/puppeteer
6:10:44 AM 10/15/2020: > node install.js
6:10:50 AM 10/15/2020: Chromium (800071) downloaded to /workspace/node_modules/puppeteer/.local-chromium/linux-800071
6:10:51 AM 10/15/2020: > hugo-extended@0.76.4 postinstall /workspace/node_modules/hugo-extended
6:10:51 AM 10/15/2020: > node lib/install.js
6:10:53 AM 10/15/2020: ✔ Hugo installed successfully!
6:10:53 AM 10/15/2020: npm notice created a lockfile as package-lock.json. You should commit this file.
6:10:53 AM 10/15/2020: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
6:10:53 AM 10/15/2020: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
6:10:53 AM 10/15/2020: npm WARN graphviz-cli@1.0.0 requires a peer of canvas@2.6.1 but none is installed. You must install peer dependencies yourself.
6:10:53 AM 10/15/2020: npm WARN specs@1.0.1 No repository field.
6:10:53 AM 10/15/2020: added 945 packages from 425 contributors and audited 947 packages in 27.973s
6:10:54 AM 10/15/2020: 123 packages are looking for funding
6:10:54 AM 10/15/2020: run `npm fund` for details
6:10:54 AM 10/15/2020: found 1 high severity vulnerability
6:10:54 AM 10/15/2020: run `npm audit fix` to fix them, or `npm audit` for details
6:10:54 AM 10/15/2020: > specs@1.0.1 build /workspace
6:10:54 AM 10/15/2020: > npm run build-diagrams && hugo && npm run build-toc && hugo --gc --minify
6:10:54 AM 10/15/2020: > specs@1.0.1 build-diagrams /workspace
6:10:54 AM 10/15/2020: > tools/diagrams.js
6:10:54 AM 10/15/2020: Processing *.{mmd,dot}
6:11:06 AM 10/15/2020: Processed *.{mmd,dot}: 11.840s
6:11:06 AM 10/15/2020: Start building sites …
6:11:09 AM 10/15/2020: | EN | PT
6:11:09 AM 10/15/2020: -------------------+-----+------
6:11:09 AM 10/15/2020: Pages | 188 | 9
6:11:09 AM 10/15/2020: Paginator pages | 0 | 0
6:11:09 AM 10/15/2020: Non-page files | 56 | 0
6:11:09 AM 10/15/2020: Static files | 172 | 172
6:11:09 AM 10/15/2020: Processed images | 0 | 0
6:11:09 AM 10/15/2020: Aliases | 3 | 2
6:11:09 AM 10/15/2020: Sitemaps | 2 | 1
6:11:09 AM 10/15/2020: Cleaned | 0 | 0
6:11:09 AM 10/15/2020: Total in 2892 ms
6:11:09 AM 10/15/2020: > specs@1.0.1 build-toc /workspace
6:11:09 AM 10/15/2020: > tools/toc.js
6:11:10 AM 10/15/2020: Building toc.json
6:11:13 AM 10/15/2020: Updated toc.json
6:11:13 AM 10/15/2020: Built toc.json: 3.012s
6:11:13 AM 10/15/2020: Start building sites …
6:11:16 AM 10/15/2020: | EN | PT
6:11:16 AM 10/15/2020: -------------------+-----+------
6:11:16 AM 10/15/2020: Pages | 188 | 9
6:11:16 AM 10/15/2020: Paginator pages | 0 | 0
6:11:16 AM 10/15/2020: Non-page files | 56 | 0
6:11:16 AM 10/15/2020: Static files | 172 | 172
6:11:16 AM 10/15/2020: Processed images | 0 | 0
6:11:16 AM 10/15/2020: Aliases | 3 | 2
6:11:16 AM 10/15/2020: Sitemaps | 2 | 1
6:11:16 AM 10/15/2020: Cleaned | 0 | 0
6:11:16 AM 10/15/2020: Total in 2381 ms

**Comment by andyschwab** [comment]
Update: logs should now appear properly for all Fleek builds in PRs to ease debugging.
