### ISSUE TITLE
(Proposal) Multiple Sector Size

### ISSUE THREAD

**Issue by bvohaska** [filecoin-project/specs#175]
**Motivation:** Allow miners to choose sector sizes and proof sizes, improving scaling & usability.

**The procedure:**

- `storage client` needs to be able to state that they prefer one class of sector over another
    - Definition: `sector class` is a predefined tuple (Groth parameters/verification key, proof size,  sector size) that is supported by FIL. Support in this context means there is tooling--understood by all FIL clients--that tells the client how to prove existence of data in this `sector class`.
    - This implies that all sector classes must have a trusted setup.
    - Note that different sector classes may have the same sector size.
    - This also implies that each sector class will have its own (large) Groth parameters.
  1. client looks for ask (on a particular sector class) - “Price per data for a sector size”
  2. client places a bid for the ask they found
  3. storage deal is consummated and piece-bytes are transferred to the miner

**Questions:**
- Does `sector builder` need to be modified to support multiple `sector classes`?
  - Do we need a naming convention for these different `sector classes`?
    - (alpha, beta, whatever)? Probably not. 
    - Tuple (public params)? <--Probably best choice
    - ...
- Do asks need a sector class associated with them? 
  - Probably not b/c (1) - Clients only care about sector size.
  - Choice of `sector class` is partially up to miners; client is unaffected by proof size but is affected by sector size (which influences retrieval speed).
- Do bids need a `sector class` associated with them?
  - No, only sector size.
  - Miners can choose `sector class` that supports the clients chosen sector size
- Does `commitSector` message need `sector class`?
  - Yes, the chain needs to know the sector size in order to update the power table.
  - The chain needs to know the proof size; implicit in the proof provided.
  - Meta-question: Why can the chain trust the miners self-reported storage size? The reason self-reporting is ok: there is a deterministic mapping between `sector classes` and verification keys. Thus, if the proofs verify given a verification key then the storage claim must be correct. (Space hardness assumption in PoS).
- Should supported sector classes be enumerated?
  - We could have an implicit list of supported sector classes that work for only supported SNARK verification keys. A proof in any unsupported sector class will fail verification. I.e. Sector size becomes a public parameter of {PoRep & PoST} and verification keys are tied to public parameters. So it is infeasible to use unsupported sector sizes without error.

**How one might specify sector sizes*:*

- Use actual size (exponential representation of some form) to name `sector class`
  - `commitSector` can receive actual size and cannot be tricked (proof required)
  - Size is on chain
  - Size is public input to circuit
    - Circuit knows about size
    - Size can be verified in circuit
    - Therefore, actors/chain don’t need to know about ‘valid sizes’
    - Any valid proof reports its own size for power table.
    - New sector sizes can be brought on line by publishing new circuits/params.
      - Corollary: any verifying key clients use blesses corresponding proofs
      - This was always true, but this case emphasizes that validation of keys as canonical part of ‘state’ (as code is) is important.
        - Tangent: we need a mechanism for specifying valid verifying keys. First suggestion: merkle root of all verifying keys is published and updated if set changes. 
    - If we really don’t like this property, we could still put explicit checks in relevant actors — but it actually seems like a natural and valuable one.
- We could have a minimum space unit (example: 1 KB) and representation (x,y) 
  - X: 1 = KB, 2 = MB, 3 = GB, ..
  - Y: 1 = 2^1, 2 = 2^2, …
  - We could have reasonable bounds on these numbers X <= 6 (exabytes) and Y <= 10 (1024). 
  - We will not support all 60 possibilities but even if we did this fits in an 8-bit string
- Flexible payload size
  - Definition: verified single tenancy is an optional condition with public input that tells a miner to individually address a clients data and put the resulting parameters on-chain.
  - A client gives data of size(data) < sector size and specifies verified single tenancy 
  - Miner packs `piece` in the smallest supported sector size that will contain the data and zero pads to the end of the sector
  - Miner includes the actual data size as a component of the `replica id`
    - This means that the data size is a public input into PoRep-Offline (`SEAL`) proof
    - This allows public verification of single-tenant data without need to encode length in meta-data.
    - Example: I store exactly 987,654 bytes.
      - My piece is packed as the only piece in the smallest sector in which it will fit.
      - There is a canonical `commD` associated (by zero padding).
      - This `commD` is shared by many other pieces (with trailing zeroes).
      - Mine is unambiguously specified because data length is hashed into `replica id` and must be supplied as a public parameter.
     - We should support this workflow explicitly with tooling for checking such single-tenant `commD`s.
     - We may want to also provide query support for counting/locating known `commD`s on-chain.
     - This directly supports use-cases in which an entity wishes to publicly and verifiably claim there exist > N replicas of a particular binary.

For wareness: @whyrusleeping, @nicola

**Comment by whyrusleeping** [comment]
Good summary, responding to some of the questions:

> we need a naming convention for these different sector classes

How about we just denote them by their sizes?

> do asks need a sector class associated with them?

I don't think asks explicitly need to have the sector size associated with them, but miners should be able to specify different prices for different sizes of data. So to achieve that, we should probably allow asks to specify a size range.

> should supported sector classes be enumerated? 

Yes, we should explicitly state what sizes are supported.

**Comment by porcuquine** [comment]
Some quick responses. I will flesh some of this out better in an editing pass.

> How about we just denote them by their sizes?

This is what the proposal wants to suggest. If not clear, I will make it clear.

> I don't think asks explicitly need to have the sector size associated with them, but miners should be able to specify different prices for different sizes of data. So to achieve that, we should probably allow asks to specify a size range.

Interesting. I think the effective cost of different sector sizes will always differ, so I wonder how much value there is in supporting ranges. That is, I suspect reasonable miners will want to create a separate ask for each size they support.

> Yes, we should explicitly state what sizes are supported.

Does your answer apply also to proof sizes, or can this be entirely handled by the mechanism (to be described — but absent above) for validating verifying keys? The latter would make it easiest to add support for new configurations over time — though it's not a deal-breaker either way.

**Comment by porcuquine** [comment]
Also a little more follow-up about 'explicitly state what sizes are supported': This needs to happen so miners can opt into the groth parameters for sector classes (sector size, proof size) they care about. If we support ranges in asks, then clients need to know what specific sizes are valid. If we *don't*, then clients know what is valid by the existence of a corresponding ask (or not).

**Comment by porcuquine** [comment]
@whyrusleeping I made a few edits above. Nothing major, but it's worth re-reading just to check.

**Comment by laser** [comment]
> Q: Do asks need a sector class associated with them?
> A: Probably not b/c (1) - Clients only care about sector size. Choice of sector class is partially up to miners; client is unaffected by proof size but is affected by sector size (which influences retrieval speed).

I don't understand this answer. 

Suppose I am a client who wants to store a piece. There exist two asks, each of which can accommodate my piece. One ask is of class X and the other Y. Retrieval speed is important to me, and fast is better. I want to choose the ask which will accommodate my piece and is also provides the best (fastest) retrieval characteristics. 

If asks do not have a sector class associated with them, how can I choose the ask which best fits my needs?

**Comment by laser** [comment]
> Definition: verified single tenancy is an optional condition with public input that tells a miner to individually address a clients data and put the resulting parameters on-chain.

Does "single tenancy" in this context imply that a client (a tenant) can store multiple, distinct pieces in the same sector? Does this definition imply that a single tenant sector will hold only a single piece?

> A client gives data of size(data) < sector size and specifies verified single tenancy

How will single tenancy be specified by the client? Will the client specify single tenancy as part of their bid?

**Comment by laser** [comment]
> We should support this workflow explicitly with tooling for checking such single-tenant commDs.

Just so that I can be sure that I follow: A client must be able to verify that their piece was the only piece sealed into a sector whose commitments appear on-chain if the miner agreed to single tenancy. Since CommD will be the root hash a merkle tree over the (preprocessed) pieces in the yet-to-be-sealed sector-file - and the only piece in the sector is the client's piece - the client will be able to compute this CommD and compare with the CommD in the `commitSector` message. Did I get that right?

**Comment by porcuquine** [comment]
@laser 

> Suppose I am a client who wants to store a piece. There exist two asks, each of which can accommodate my piece. One ask is of class X and the other Y. Retrieval speed is important to me, and fast is better. I want to choose the ask which will accommodate my piece and is also provides the best (fastest) retrieval characteristics.
> 
> If asks do not have a sector class associated with them, how can I choose the ask which best fits my needs?

If asks contain sector size, then you select the one that has the retrieval characteristics you want and is large enough for your piece. You don't directly care about proof size, so any `sector class` with your chosen sector size meets your requirements.

The point you *may* have missed is that many `sector classes` may have the same `sector size`.

Does that clarify?

**Comment by porcuquine** [comment]
@laser 

> > Definition: verified single tenancy is an optional condition with public input that tells a miner to individually address a clients data and put the resulting parameters on-chain.
> 
> Does "single tenancy" in this context imply that a client (a tenant) can store multiple, distinct pieces in the same sector? Does this definition imply that a single tenant sector will hold only a single piece?

Although not elaborated above, it should refer to a single piece. If one client wanted to store multiple logical files in this way, they could/should do the aggregation themselves. The reason we need first-class support at all is to distinguish padding amounts. The intended guarantee of a unique `commD` depends on there only being a single verified piece.

> > A client gives data of size(data) < sector size and specifies verified single tenancy
> 
> How will single tenancy be specified by the client? Will the client specify single tenancy as part of their bid?

It could be done that way, and this would be a very small change (one bit of information added).

Technically, this does not need to be in the protocol at all because it could be communicated out-of-band. The critical point is that we need a small protocol change to make it possible to *verify* that this has happened. We should (eventually) provide a utility to support this verification, so that given a piece, I can compute the expected `commD` and confirm the validity of any replica claiming to host the corresponding data. Although this can be accomplished with a piece inclusion proof, actually posting PIPs on chain is an expensive dispute-resolution mechanism we seek to avoid.

**Comment by porcuquine** [comment]
@laer

> > We should support this workflow explicitly with tooling for checking such single-tenant commDs.
> 
> Just so that I can be sure that I follow: A client must be able to verify that their piece was the only piece sealed into a sector whose commitments appear on-chain if the miner agreed to single tenancy. Since CommD will be the root hash a merkle tree over the (preprocessed) pieces in the yet-to-be-sealed sector-file - and the only piece in the sector is the client's piece - the client will be able to compute this CommD and compare with the CommD in the `commitSector` message. Did I get that right?

Yes, that's right. I answered this in my previous response (at the end) before I got to this question.

**Comment by nicola** [comment]
General concerns with multiple sector sizes:
- sectors must be greater than a minimum sector (today ~64GiB)
- having multiple DRG graphs increases the surface attack on DRGs: in other words, I don't think it's practical to attack multiple (say 10 graphs) instead of 1.

**Comment by porcuquine** [comment]
@nicola Your second point seems to say that multiple DRGs increase the likelihood of attacks, then summarize it self by saying that more graphs are less practical to attack.

These points may both be true, but I'm not sure how they relate. Are you saying that there exists a theoretical concern which we can probably ignore in practice?

**Comment by porcuquine** [comment]
Regarding your first point, I agree that multiple sector sizes will not allow us to avoid whatever security constraints are imposed on all sectors.

That said, it will provide a useful method for supporting smaller (than, say, 64 GiB) sectors for development purposes while also supporting larger, secure sectors as we move toward launch.

**Comment by laser** [comment]
## Will a Miner Be Able to Generate a Single PoSt over Sectors of Different Sizes?

As per the spec, `SECTOR_SIZE` is a VDF PoSt public parameter. This implies that all of the CommRs passed to the PoSt.generate routine must correspond to sectors of the same size. Will this invariant change when we support multiple sector sizes? 

If not, this means that a mining rig-operator will need to run N-number of PoSt.generate operations in parallel, where N is the number of sector sizes which they have committed to the network. PoSt generation consumes a core for approximately the duration of a miner's proving period, so N is bounded by the mining rig's cores.


## Should Proving Period Length (in Blocks) Reflect the Size of a Sector?

The amount of time it takes to generate a PoSt over small sectors is less than the amount of time that it takes to generate a PoSt over large sectors. We think this is needed to prevent generation attacks because we think sealing smaller sectors takes less time. This implies that the number of blocks in a miner's proving period should reflect the size of the sectors which they are proving. Is that correct?


## Will Filecoin Support Different PoSt Proof Sizes?

From the spec proposal:

> Definition: sector class is a predefined tuple (Groth parameters/verification key, proof size, sector size) that is supported by FIL.

Will Filecoin support different PoSt proof sizes - or just different seal proof sizes? The items (key, proof size, sector size) in the tuple suggest that Filecoin will NOT support different PoSt proof sizes.


## What Unit Do We Measure Power In?

Today, the power table reflects the number of sectors which a miner has committed to the network. This will need to change to support multiple sector sizes. What unit should we measure power in? Minimum sector size? If so: What is the minimum sector size?


## Does a Miner Need to Specify Sector Size When Pledging?

Does the miner need to specify a sector size when pledging? Today, a miner pledges a quantity of bytes and provides collateral. It may be the case that this remains unchanged in a multiple sector size world, but we're not sure.

If a miner does need to specify sector size when pledging, must they be allowed to change their sector size after pledging? If so, what happens to the miner's existing (unfulfilled) asks?


## Will a Single Miner Actor Commit Sectors of Different Sizes?

This question relates to the previous question. Will miner operators who want to offer sectors of different sizes need to create multiple miner actors? Or will they create a single miner which commits sectors of different sizes? I have heard a rumor that mining operators may simply run multiple go-filecoin nodes (one per sector size which for which they have asks).


## Why Would Anyone Use Big Sectors?

To meet scaling requirements, Filecoin must support big sectors. It's our belief that hobbyist miners will not be able to seal big sectors due to hardware constraints. To enable hobbyist miners to participate in the network, we must also offer smaller sectors.

Why would a mining rig operator use big sectors instead of small sectors? To save on gas?


## How Do Single Tenant Sectors and Support for Multiple Sector Sizes Relate?

The spec proposal says that:

> verified single tenancy is an optional condition with public input that tells a miner to individually address a clients data and put the resulting parameters on-chain.

It's not clear to us how single tenancy and supporting multiple sector sizes relate. Our guess is that by allowing miners to create asks for small sectors that it may become cost effective for clients to buy an entire sector (i.e. opt-in to single tenancy). Is our intuition correct?

**Comment by porcuquine** [comment]
> ## Will a Miner Be Able to Generate a Single PoSt over Sectors of Different Sizes?
> As per the spec, `SECTOR_SIZE` is a VDF PoSt public parameter. This implies that all of the CommRs passed to the PoSt.generate routine must correspond to sectors of the same size. Will this invariant change when we support multiple sector sizes?
> 
> If not, this means that a mining rig-operator will need to run N-number of PoSt.generate operations in parallel, where N is the number of sector sizes which they have committed to the network. PoSt generation consumes a core for approximately the duration of a miner's proving period, so N is bounded by the mining rig's cores.
> 

PoSt will still be performed with uniform-sized sectors. There will need to be distinct PoSts for every sector size a miner has sealed. These will be effectively 'parallel universes' for each sector size into which a miner has opted. In this version of reality, each 'universe' may have its own proving period.

> ## Should Proving Period Length (in Blocks) Reflect the Size of a Sector?
> The amount of time it takes to generate a PoSt over small sectors is less than the amount of time that it takes to generate a PoSt over large sectors. We think this is needed to prevent generation attacks because we think sealing smaller sectors takes less time. This implies that the number of blocks in a miner's proving period should reflect the size of the sectors which they are proving. Is that correct?

This is correct. The relationship between sealing time and polling time does affect proving period. The strength of this dependency is affected by choice of PoSt, and is mitigated by use of VDF (@nicola may be able to comment in more detail). However, in general, we should assume that proving period is a function of sector size.

> 
> ## Will Filecoin Support Different PoSt Proof Sizes?
> From the spec proposal:
> 
> > Definition: sector class is a predefined tuple (Groth parameters/verification key, proof size, sector size) that is supported by FIL.
> 
> Will Filecoin support different PoSt proof sizes - or just different seal proof sizes? The items (key, proof size, sector size) in the tuple suggest that Filecoin will NOT support different PoSt proof sizes.
> 

When extended to consider PoSt, the tuple should include both PoRep proof size and PoSt proof size. The same goes for Groth parameters and verification keys. A change in sector size will affect groth parameters/keys. Each supported proof size will require distinct parameters/keys. Proof sizes for PoRep and PoSt should be independently selectable if the choice exists.

> ## What Unit Do We Measure Power In?
> Today, the power table reflects the number of sectors which a miner has committed to the network. This will need to change to support multiple sector sizes. What unit should we measure power in? Minimum sector size? If so: What is the minimum sector size?

The actual unit should be bytes, though we can probably use a larger unit for both the power table and as a parameter when reporting/requesting sector sizes. Note, however, that the only benefit of doing this is compression. For that reason, it might make most sense simply to use bytes everywhere except on chain — and to define the on-chain representation as simple compression.

The minimum sector size is a plausible choice, but it would require committing to a minimum sector size. If we decide we want to do this, it might well be that we do not actually support use of that minimum sector size initially (or ever) in order to be conservative about our limits.

If I had to make a guess right now, I would suggest that the power table be denominated in 1GiB units and everything else (where compression is not an issue) be denominated in bytes — just as the FPS already returns bytes when queried for max data that can be stored in a sector.

> 
> ## Does a Miner Need to Specify Sector Size When Pledging?
> Does the miner need to specify a sector size when pledging? Today, a miner pledges a quantity of bytes and provides collateral. It may be the case that this remains unchanged in a multiple sector size world, but we're not sure.
> 
> If a miner does need to specify sector size when pledging, must they be allowed to change their sector size after pledging? If so, what happens to the miner's existing (unfulfilled) asks?
>

It's not clear to me that pledging needs to be affected by multiple sector sizes. @whyrusleeping may have more insight.
 
> ## Will a Single Miner Actor Commit Sectors of Different Sizes?
> This question relates to the previous question. Will miner operators who want to offer sectors of different sizes need to create multiple miner actors? Or will they create a single miner which commits sectors of different sizes? I have heard a rumor that mining operators may simply run multiple go-filecoin nodes (one per sector size which for which they have asks).

Either would (I think) be fine from my perspective. The spirit of this proposal is to support multiple sector sizes for a single miner, though. This is an area where information about the implementation complexity of one approach versus the other would be useful input into the decision.  I think these two paths are quite different and probably have a lot of implications which shouldn't necessarily be forced by the need (if it is established) to support multiple sector/proof sizes. Rather, we should consider those implications when deciding how the proposal should be implemented.

> ## Why Would Anyone Use Big Sectors?
> To meet scaling requirements, Filecoin must support big sectors. It's our belief that hobbyist miners will not be able to seal big sectors due to hardware constraints. To enable hobbyist miners to participate in the network, we must also offer smaller sectors.
> 
> Why would a mining rig operator use big sectors instead of small sectors? To save on gas?

Yes, that is the main reason, but see below:

1. Both larger sectors and smaller proofs increase the data-to-proof-size ratio, which reduces the average cost of both accumulating power and of providing storage to the storage market. The scalability requirements relate to cost-efficiency of mining, so miners benefit from operating 'at scale' for the same reason we want to facilitate it. The network benefits if mining is affordable.

2. Larger sectors also increase the data-size-to-CPU-time ratio which also boils down to efficiency of operation, with all the previous considerations. The reason this is the case is that the CPU cost of proof generation increases as the log of the sector size. Therefore, larger sectors prove more data per CPU-hour than smaller sectors do.

3. Security: There will be some minimum sector size determined by the minimum polling time. It is conceivable that this minimum sector size is impractical for hobbyists. It's conceivable that we nevertheless want to support these small-but-insecure sectors for some period of time. Anyone who intends to mine at scale would be well advised to build their operation based on larger sector sizes, though — since any scaled-down feature provided for experimentation/development/convenience will not be guaranteed viable by mainnet (or likely testnet).

> 
> ## How Do Single Tenant Sectors and Support for Multiple Sector Sizes Relate?
> The spec proposal says that:
> 
> > verified single tenancy is an optional condition with public input that tells a miner to individually address a clients data and put the resulting parameters on-chain.
> 
> It's not clear to us how single tenancy and supporting multiple sector sizes relate. Our guess is that by allowing miners to create asks for small sectors that it may become cost effective for clients to buy an entire sector (i.e. opt-in to single tenancy). Is our intuition correct?

That is true. It is also the case that the ability to specify an 'actual data size' distinct from the storage power credited for a given sector introduces a more nuanced meaning to sector size in context.

It's likely that smaller sectors will be more expensive per byte, so it's theoretically possible that for single-tenancy situations where fast retrieval is not required, clients would select a larger sector size than the minimum. This is something that the market would sort out, and I mention it mostly to emphasize that 'actual data size' introduces a new, independent dimension. In that sense, it could have beeb introduced as an independent proposal and could likewise be accepted or rejected independently.

**Comment by laser** [comment]
@porcuquine 

Two things which you said:

> It's not clear to me that pledging needs to be affected by multiple sector sizes. @whyrusleeping may have more insight.

> The spirit of this proposal is to support multiple sector sizes for a single miner, though. This is an area where information about the implementation complexity of one approach versus the other would be useful input into the decision. I think these two paths are quite different and probably have a lot of implications which shouldn't necessarily be forced by the need (if it is established) to support multiple sector/proof sizes. Rather, we should consider those implications when deciding how the proposal should be implemented.

-----

I think that we can significantly reduce the amount of code required to support multiple sector sizes if:

1. A miner selects a sector class when pledging (i.e. when `miner create` command runs)
1. A go-filecoin node can have (at most) one miner actor (this invariant exists today)
1. A SectorBuilder manages sectors for exactly one miner actor (this invariant exists today)

The implication is that someone who wants to offer up multiple sector sizes will need to operate multiple go-filecoin nodes.

Is that an acceptable solution, @whyrusleeping @porcuquine @jbenet ?

**Comment by porcuquine** [comment]
With the following assumptions, my answer is yes:

1. I am speaking only from the perspective of the FPS and its implementation. (I'm not attempting to address broader considerations — so others who represent them should also comment.)
2. As I read this option, it doesn't impose any added constraints or restrictions on the FPS. If I've misinterpreted the implications, we should discuss further so we are on the same page.

Also, please note that, as I read it, this does not address multiple proof sizes — so I assume this would still allow for variable proof size everywhere.

**Comment by laser** [comment]
@porcuquine 

> Also, please note that, as I read it, this does not address multiple proof sizes — so I assume this would still allow for variable proof size everywhere.

A sector class implies a choice of proof size, does it not?

Anyways, what I propose (above) is that a miner actor be created with a **single** tuple of (Groth parameters/verification key, sector size, PoSt proof size, and seal proof size). 

This property means that we can initialize the node's SectorBuilder with said tuple and that the choice of sector size and proof size(s) will remain fixed for the lifespan of the SectorBuilder (and its miner actor), which makes piece-adding, sealing, and metadata management straightforward. It also means that a miner actor will have only one proving period to track.

**Comment by porcuquine** [comment]
Right, I missed 'sector class' in your text.

I don't have a problem with this proposal. I think we can make it work on the proofs side, and I also think it cooperates with the likely use cases for miners. That is, I don't think committing to a limited selection of the available combinations is a liability. If anything, this may simplify configuration.

**Comment by laser** [comment]
I spoke to @whyrusleeping about this today. In summary: The protocol should permit that a miner actor commit sectors of different classes.

**Comment by nicola** [comment]
**Alternative to Multiple Sector Size**
Note that this is not necessarily a "NO" for multiple sector sizes, in fact I believe that multiple sector sizes is the "safest" option today in terms of implementation, but in the grand scheme it requires adding (minor?) complexity to the protocol and increases the attack surface (many proving periods, many DRG graphs).

I am mostly writing this here for reference.

**Proposal: Sector aggregation**
There is no problem in having a single sector size as long as:
- The size of the proof of chain for 64GB, 100GB, 1TB, 1PB is still constant
- The cost for the prover to generate the sealing per GB is the same

There is different way we could get "close" to this in alternative to multiple sector sizes, which is having batching SNARKs & GPU SNARKs.

Main idea:
1. Generate multiple sectors in parallel of the same size (in comparison to Multiple Sector Size (MSS): much better throughput than having larger sectors, in MSS in order to encode a 10x bigger sector, it takes 10x time)
2. Aggregate multiple sectors SEAL proofs into one (same as MSS, however, this will give a linear overhead :( in fact, if we have 10x sector vs 10 sectors, we will have to compute 10 snarks instead of 1 + batching) - Note that this might not be a provlem if we have GPU SNARKs

There is actually nothing new in what I am proposing, this has been around for a year or so, we just didn't spend much resources into getting this. 

- Pro: it looks like Filecoin proofs might require batching and GPU independently of this problem. In other words, so solving "batching snarks" and "GPU snarks" might be inevitable could help kick two birds with one stone.
- Cons: there is uncertainty on whether of these two problems will be solved by shipping time.

**Comment by porcuquine** [comment]
> There is actually nothing new in what I am proposing

@nicola Agreed.

Although it's fine to use this space to record the idea, I think what you wrote here doesn't really relate to the multiple sector size proposal itself. It may relate to the question of whether we should implement multiple sector sizes, but that discussion should happen elsewhere if needed.

**Comment by pooja** [comment]
@porcuquine What is the latest on this? Do we have enough info to PR this into the spec? Or has this proposal not yet been ratified?

**Comment by porcuquine** [comment]
This has been ratified and we are proceeding with implementation of all but single-tenant sectors, for now.

Some relevant spec changes have already been merged by #221.

Some further modifications will probably be needed, but it may make most sense to wait until the implementation has stabilized to actually update the spec.

**Comment by laser** [comment]
Just rebased; conflicts in actors.md now resolved.
