### ISSUE TITLE
clarify distinction and uses of FCS and CBOR-RPC

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#268]
Filecoin has two different encoding schemes, both are cbor based. The first, FCS (Filecoin Compact Serialization) is used for all data structures that are 'on chain'. This is the Block (header) and everything it links to (messages, state, receipts and so on).

The second scheme, CBOR-RPC, is used for network communications between filecoin peers, where 'saving every byte' matters a bit less. If an object that usually is serialized with FCS is included in a CBOR-RPC message, it should continue to be encoded with FCS.

This should be detailed more clearly in the spec

**Comment by gnunicorn** [comment]
I'd generally argue to have one or at maximum two clean and clearly defined encoding schemes for all types. Right now, encoding definitions are inconsistent and on a type-by-type basis:
 -  [`Address` defines a string-concatenation-scheme](https://filecoin-project.github.io/specs/docs/address/#encode),
 - so [do Signatures](https://filecoin-project.github.io/specs/docs/data-structures/#serialization-1)
 - while [`MessageReceipt`s are CBOR marshalled with lower case named fields](https://filecoin-project.github.io/specs/docs/data-structures/#serialization)
 - and [`Block`, `Message` and `SignedMessage` are encoded as CBOR-Arrays of their fields (in order of appereance in the spec) and prepended with an object type tag](http://localhost:1313/specs/docs/data-structures/#filecoin-compact-serialization)

The reasons for these different schemes are unclear, if intended at all.

I suggest taking a closer look at SCALE ([Section 9.1 in this draft paper](https://github.com/w3f/polkadot-re-spec/blob/master/polkadot_re_spec.pdf)), which is very similar to the concatenating system or FCS but more compact, for everything that is _on chain_ (`Messages`, `SignedMessage`, `MessageReceipts`, potentially `Actor`s as well?) and thus must be super compact. This, of course, could also be used for Network Transfers and messages on the network, but I think there it doesn't matter to have them this compact, and such a slightly more verbose system and flexible codec, like CBOR, could very well be expected standard. 

(But I am wondering, whether that might be something additional that the handshake message might contain and thus different encoding-formats between two peers might be negotiated - [similarly as http content negotiation works](https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation). Form a spec perspective we don't really care how the blocks are encoded in transit, thus we can easily allow for easily extending on this level without failing to spec compliant.)

**Comment by dignifiedquire** [comment]
> Address defines a string-concatenation-scheme,

The address format has different considerations than the rest of the chain data, as it is used in a human readable version, as well as on chain. We have worked hard to overcome various constraints, and I think the current encoding is in a good place, even though not fully consistent with the rest. 

> so do Signatures

I think signatures should be changed to FCS, there is little use to have them be different, afaict.

> while MessageReceipts are CBOR marshalled with lower case named fields

should move to to FCS, as well, the current state is mostly historically afaik.

In regards to network messages, we are planning to drop the length prefixing already, and just send raw cbor objects on the wire, as they already contain all information required to safely decode them from a stream. See #204 

With the updates above, we would reduce things to three cases

1. Addresses 
2. FCS, for all on-chain structures
3. Regular cbor, for everything else

--- 

> might contain and thus different encoding-formats between two peers might be negotiated 

I would caution against making formats negotiable, this makes the spec & implementations more complex, rather than simplify things.

**Comment by gnunicorn** [comment]
> I would caution against making formats negotiable, this makes the spec & implementations more complex, rather than simplify things.

The proposal would be to allow "additional codecs for wire transfers" and for wire transfers only. But that is out of scope of this ticket.

**Comment by gnunicorn** [comment]
> The address format has different considerations than the rest of the chain data, as it is used in a human readable version, as well as on chain. We have worked hard to overcome various constraints, 

Could you elaborate on them? Or is there any place I can read up on them? I don't quite understand why the block/wire encoded version of these must be the same as the human readable string (rather than a byte array). It isn't as if you'd ever "read" the fields of a block directly anyways (they are encoded either way), so where does that constrain come from? Why not have clear definitions as to how they are encoded on the wire and how they are presented to humans - like we have for CiDs?

**Comment by dignifiedquire** [comment]
> Could you elaborate on them? Or is there any place I can read up on them? I don't quite understand why the block/wire encoded version of these must be the same as the human readable string

You are right, the current byte format, which is the prefix for the signature type + raw bytes, is influenced by the considerations that were important to cover for the human readable version. 

We technically could switch that to use FCS, though in this case that would mean increasing the size of it. Alternatively for better consistency we could have a cbor tag for each of the address types, and serialize it as a byte array with that tag, instead. Which I think would not increase the size and bring consistency of FCS usage.

**Comment by gnunicorn** [comment]
Also noticed [RLE+ was added recently](https://github.com/filecoin-project/specs/pull/251), but it isn't mentioned, where it is supposed to be used?

**Comment by pooja** [comment]
We will solve this as part of: https://github.com/filecoin-project/specs/issues/352

**Comment by dignifiedquire** [comment]
This should be solved and much clearer with ipld schemas now
