### ISSUE TITLE
Clarify use of signatures in EC

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#290]
The EC spec mentions that the Election Proof is the output of a VRF, and we mention that we use a signature to implement the VRF, but we don't specify which signature algorithm to use. Since this has not been made clear, and since specs for BLS signatures have not yet landed, go-filecoin has moved forward using secp256k1. This is not great as ECDSA signatures are not deterministic, and miners can just keep generating different signatures until they find a winning election proof.

**Comment by whyrusleeping** [comment]
In the same set of work, we should probably also clarify the exact functions used to generate tickets and election proofs (including hash functions, lengths of things, etc).

@sternhenri do you think you could take this on?

**Comment by sternhenri** [comment]
Yes. I can make proposals for all of these. Will do so in this issue before we move to PR or anything like that.

**Comment by bvohaska** [comment]
Proposed first pass: #334

Feel free to run with it

**Comment by sternhenri** [comment]
- + modify order so it is VRF then VDF, rather than VDF + VRF (which means miners must all run a VDF but no sharing of VDFs when running attacks or simulations)

**Comment by sternhenri** [comment]
Thanks @Austin-Williams. We'd actually specc'd the EC-VRF usage to date but are now moving toward using BLS signatures for our VRF (cc @nikkolasg ).

**Comment by Austin-Williams** [comment]
> but are now moving toward using BLS signatures for our VRF

Rather than using the BLS signature _directly_ for the VRF, we may want to consider running the BLS signature through a secure hash function, and using the output of the hash function as the VRF output.

The BLS signature guarantees uniqueness of the output, but it does not (by itself) guarantee that the output is indistinguishable from uniform randomness. (The signature is certainly _unpredictable_ to an attacker, but it is not guaranteed to be indistinguishable from uniform randomness).

When the BLS signature is passed through a secure hash function, that should provide both uniqueness (from the BLS sig) and indistinguishability from uniform randomness (from the hash function).

Since the VRF is intended to be used for leader selection, the "indistinguishability from uniform randomness" property is important. In particular, we never want to worry that an attacker controls a set of keys whose signatures tend to favor the selection of one of themselves as the next leader.
