### ISSUE TITLE
Document payments channel actor in actors.md

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#311]
The payment channel construction in payments.md needs to be transferred to actors.md and use the same format as the rest of the system actors.

**Comment by anorth** [comment]
Note also that I think the implementation is slightly more generic than the spec, with a condition predicate (actor method and params) instead of hard-coding piece inclusion proof verification as the only and required condition.

https://github.com/filecoin-project/go-filecoin/blob/master/actor/builtin/paymentbroker/paymentbroker.go#L89

@acruikshank 

(Sorry if this derails an otherwise straightforward issue; feel free to break it out. That the implementation does not include multiple lanes is also separate issue).

**Comment by whyrusleeping** [comment]
Yeah, i remember discussing that at one point. The change hasnt happened yet. If we want to do something like that, a PR should be made to the spec. As it stands, the go-filecoin implementation you linked is not spec compliant.

**Comment by pooja** [comment]
@anorth Is there an issue in go-filecoin tracking making this part of the implementation spec-compliant?

**Comment by anorth** [comment]
There is https://github.com/filecoin-project/go-filecoin/issues/2835 for adding the already-implemented condition/predicate to the spec.

(There is no issue for implementing multi-lane payment channels because it's not on our near-term plan. We're not close enough yet to file an issue for everything not yet in sync.)
