### ISSUE TITLE
Define early and duplicate PoSt behaviour

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#337]
A miner must submit a valid PoSt before the end of a proving period in order to avoid penalisation (a late fee). The proving period is tracked by a single state variable, `ProvingPeriodEnd`, being the deadline to avoid fees. At present, the spec sets the subsequent proving period end to be the old one + the fixed period duration. If a miner submits a PoSt quite early (perhaps due to superior hardware) this gives the miner an actual duration to compute the next proof that is longer than the proving period, and if repeated this additional time could compound (a comment in the spec calls this out).

This opens up a generation attack, so either:
- the subsequent proof should be impossible to begin until the start of its proving period, or
- the new proving period should start when the PoSt is actually submitted, not when it was due

The intended dependence of proof verification on the chain is not captured in the spec yet: `CheckPostProofs(miner.SectorSize, proofs, faults)` needs parameters like chain height and miner's proving period. The spec doesn't reference sampling chain randomness for proofs (but does for block-mining ticket randomness).

Go-filecoin currently contains chain randomness sampling code which does tie the proof to the chain, but on my reading, it does not prevent early proof calculation.

Separate but simpler, a miner might submit the same proof multiple time (e.g. b/c they have multiple redundant proving nodes and a race condition). The semantics of this should be clear, and the simple answer is that a duplicate proof is simply declared invalid (b/c it refers to a prior proving period), with no penalty beyond gas fees.

**Comment by nicola** [comment]
One reason why I mentioned allowing for early PoSt submission is because it could reduce a lot of work on faults & proofs that we might be doing.

Intuition: a miner runs into a fault, it halts the current posts, it restart the post removing the faulty sector and posts on chain the halted PoSt reporting the faults. In this way there should be no special fault handling done in proofs.

**Comment by whyrusleeping** [comment]
In order for a miner to submit their post early, or start their next one early, they would have to predict the random beacon values from the chain. Since you need randomness from the block at height `ProvingPeriodStart`, you would only be able to start your post before then if you were able to create that block yourself and know that your block would be accepted (possible in some 51% attack type scenarios).

Additionally, since the post requires randomness from `ProvingPeriodEnd - 1` (or so, may not be exactly one back, but its not too much more than that), you cannot submit your post earlier than that, for the same reasons.

@nicola we discussed this heavily, so i'm not certain that the thing you are confused about is the same as what @anorth is mentioning. It sounds like you are thinking about changes to the current PoSt construction, which is discussion that does not belong in the specs repo (as it can be confusing to be discussing many different constructions that arent the right one).

**Comment by anorth** [comment]
It does sound like @nicola is proposing something different, and agree that might best be discussed elsewhere first.

What you say about sampling randomness sounds good, thanks. It isn't clear in [SubmitPost](https://github.com/filecoin-project/specs/blob/master/actors.md#submitpost) yet, and go-filecoin implements something that is probably wrong.

**Comment by whyrusleeping** [comment]
yeah, `CheckPostProofs` needs to be more clearly defined.

@porcuquine @laser do you think one of you could bridge that gap?

**Comment by porcuquine** [comment]
I nominate @laser to look into this for now, since it will be hard for me to chase things down short term (OOO). If still unresolved when I'm back to normal, I'll dig in and sort it out.

**Comment by pooja** [comment]
Closing in favor of https://github.com/filecoin-project/specs/issues/375
