### ISSUE TITLE
VDFs for EC

### ISSUE THREAD

**Issue by sternhenri** [filecoin-project/specs#399]
EC currently relies on VDFs. There is a sense that they are likely to be significantly abused by a powerful adversary, and appropriate mitigations to account for this, but net-net, it seems preferable that we include them to help pace block times, prevent "free" simulations of future blockchains, etc.

I don't believe speccing precise VDF usage has been done yet. @nicola @whyrusleeping, is this understanding right? Worth kicking this off (via PR)?

cc @nikkolasg

**Comment by sternhenri** [comment]
Note that we can't precisely use tickets (derived from the VDFOutput) until we have this.

**Comment by nikkolasg** [comment]
>  prevent "free" simulations of future blockchains,

Do you mean nothing-at-stake problem ? If yes, incentives mechanisms such as collateral are used in other systems to defeat that attack (like in Eth or Dfinity). 

> to help pace block times

Maybe I'm just too much reluctant with VDF but it seems to me very lightweight to justify using VDF. For example Algorand doesnt use VDF and don't need them to pace block times, and I believe the reason is  because of the super majority assumption (so honest node wont sign "too-much-in-advance" block).  Would it be enough to rely on the majority assumption as well ? I can't say for sure, but I'm sure other blockchains have done it as well.

Anyway, I dont want to loose time arguing as well: if you all agree using VDF is simpler and are OK with using VDF then let's go.

**Comment by whyrusleeping** [comment]
@nikkolasg I'm actually in favor of not shipping filecoin V1 with VDFs in consensus. I don't think we get enough from it to justify the costs.

Costs:
- Block headers become significant larger
- Average miners have to burn extra CPU, while large miners will have dedicated hardware to do this very fast for very cheap
- Extra verification time complexity (~1ms in the good case per VDF) 
- More things to write and test and audit

**Comment by nikkolasg** [comment]
@whyrusleeping I agree with your costs but I still believe we should try to convince ourselves that EC without VDF is still secure because maybe the analysis depends on it - @sternhenri is the point to go here I believe. 

Or if we don't go with V1 but quickly realize we need to include them, we need to have a way to include them in the chain without forking ?

**Comment by whyrusleeping** [comment]
@nikkolasg theres no way to change something like that without a fork unless you have them already integrated, and some measurable thing everyone comes to consensus on that flips the switch to turn them on (plus all the data structures in place for that).

Agree we should get @sternhenri to look into the security without VDFs so we can make this decision.

**Comment by sternhenri** [comment]
Per your above point @nikkolasg, I meant more for long-range attacks than NaS.

That said, I reckon I'm easily convinced we can ship without it, though would like to have a conversation with Sarah to confirm my thinking (Cc @ZenGround0 as well).

From [this doc](https://docs.google.com/document/d/1op6V6msBCnOksLsQie08bJDWK9g6B8qFHhTB8Y47Yt4/edit)(not public, sorry) which remains source of truth imo, and [this issue](https://github.com/filecoin-project/consensus/issues/25) VDFs help with:
- miners rushing; though given likely AMax values, VDFs don't fully solve it and impact is mitigated by BTC-style block delay enforcement
- Posterior corruption: not at risk imo, given verifiable resource commitment (see https://github.com/filecoin-project/consensus/issues/17)
- Costless ticket grinding: mitigation is null block penalization, per https://github.com/filecoin-project/specs/pull/341 and https://github.com/filecoin-project/consensus/issues/16.

The last is my biggest concern. It seems to me like this is the most concerning cost of getting rid of vdf whereby miners substitute storage power for CPUs and parallelize ticket creation to find a winning ticket quickly. It seems to me you can do better than AMax in this case. However, I don't think it's a deal breaker, and we could see this occuring in Testnet...

**Comment by sternhenri** [comment]
Status quo, per @nicola and I (cc @jbenet) is that we will optimally move toward solution 3 provided cryptolab can spend cycles on it (cc @porcuquine), in the interim we will assume the suboptimal default for launch to be 2.

need guidance from group on how to move this forward.

**Comment by porcuquine** [comment]
Quick note that I'm not up to speed on this. Will look more later, but am very crunched at the moment.

**Comment by nikkolasg** [comment]
Let me add some thoughts w.r.t to the VDF usage in Filecoin vs Eth2. The main issues are explained in the sub-bullets **security** and **timing** at the end.

**Eth2 Context:** All explanations are derived from Justin's [post](https://ethresear.ch/t/minimal-vdf-randomness-beacon/3566) and some are of my own understanding:
  - **Time**: A block is produced during a 8 seconds time slot (number must have changed since then), and an epoch is defined as 128 slots. For each slot in a period, there is an assigned block proposer (only one AFAIU).
  - **Randao**: This is the first biasable randomness generation protocol used. Each block proposer reveals its local randomness in the block in his assigned slot. The epoch-wide randomness e_i is created by XORing all revealed randomness for all slots in epoch i.
  - **VDF**: The e_i randomness is given as input to a VDF function that takes Amax *epochs* to run. In this context, even only one honest VDF "producer" in the network is enough since the seed is common. 
    + **Rationale**: Since the input is determined at the end of epoch i, even if the attacker can run the VDF with Amax advantage, it will still take him 1 epoch to produce. Therefore, if it won't be able to "grind" because the output of the last slot of epoch i will have been determined by long. The attacker must run with a 128 * Amax advantage to be able to maybe grind *once*.
    + **Usage**: the VDF is used as a randomness generation primitive in eth2 and only the timing assumption is used, and it seems pretty conservative.
 
**Filecoin Context**: There are two major differences as to how FL uses VDF vs Eth2 with each difference implying major change w.r.t to usage in Eth2 that seems quite light.
  - **Goal**: VDF here are used to enforce time synchrony (at different layer of the protocol IIUC). As a consequence, the time bounds (let's say the  time between two blocks) are required to be set to be Amax * constant. From what I understand (and again, I may be wrong here!):
    + **Security**: Any speed advantage the attacker has is already helping him in the protocol. If he has a 2x advantage, then he can run twice the VDF. Which I believe is NOT the case in eth2 since 
    + **timing**: It imposes a high delay for time synchrony dependent on this Amax constraint - it may be not possible to use shorter bounds because of that.
  - **"Producer"**: Every miner need to run a VDF concurrently, drastically increasing the requirement on every miner instead of having altruistic VDF producer on the network.
 
I wrote this note after talking a little with "Tangkrad" (? the person that works at the EF on VDFs in some capacity) about VDF and how usage differs in eth2 vs FL. It may be valuable to talk to him if we'd like to know more about how eth2 intends to use them (and if we are using them in a non-optimal way).

**Comment by sternhenri** [comment]
The idea of being able to use a provable VDF others are running as a miner is hugely appealing, and an option @jzimmerman has been thinking of. However, it is worth understanding how much we can do this without making the synchrony assumption they make...

**Comment by nikkolasg** [comment]
I haven't found the latest update on that front but here is an [issue](https://github.com/ethereum/eth2.0-specs/issues/34) that discuss a little about the timing assumption. In short, they assume a bounded global clock shift which is inferior to their slot time. Vitalik (8 is because it's 8 seconds):
> Technically, we want networking latency plus clock disparity between all honest nodes to be <= 1 slot, so if honest node A sends a message at subjective time T, honest node B will receive the message within the subjective time interval (T - 8, T + 8) (negatives possible due to clock disparity). Though my simulations suggest things will be ok with clock disparity and/or network latency even going up to 3-4x slot duration or more, the chain just won't look as clean

Prysm will *apparently* even implement checking via NTP servers regularly to keep the time drift as small as possible [ [issue](https://github.com/prysmaticlabs/prysm/issues/511#issuecomment-421209988) ].

Note that one major difference is that there is only **one block proposer** elected in a given slot in eth2. In that manner, I believe the attacks outlined by @jzimmerman are void because there is no other blocks to "wait for" in a given slots. It feels like this supports the idea of having a timing assumptions as well.
