### ISSUE TITLE
Question on timestamp comparison in the spec

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/specs#468]
The spec right now checks a blocks timestamp with:
```
    if blk.GetTime() <= blk.minParentTime()+(BLOCK_DELAY*len(blk.Tickets)) {
```

It seems to me like we would want to just use `<` here, otherwise people who delay exactly one BLOCK_DELAY will have their blocks dropped.

**Comment by whyrusleeping** [comment]
Also, while we're here, we should define ALLOWABLE_CLOCK_DRIFT explicitly

**Comment by sternhenri** [comment]
Let's have `ALLOWABLE_CLOCK_DRIFT = worst_case_network_delay + worst_case_clock_drift + buffer`

- worst_case_network_delay:
  - Let's assume ~5 round-world trips (VPNs etc) -- https://enterprise.verizon.com/terms/latency/
  - can give 2s based on numbers here (no GCF)
  - We want to support moon mining. Moon light (348,402 km at 299,792km/s) will take 1.5s to reach earth. Say 3 to allow for some sattelite misalignement. 
  - Then we add earth latency, so we have 5s
- worst_case_clock_drift:
  - http://www.ntp.org/ntpfaq/NTP-s-sw-clocks-quality.htm#AEN1220
  - "So 500 PPM mean the clock is off by about 43 seconds per day. Only poor old mechanical wristwatches are worse." --> Good clock is closer to 69 PPM (chronometer) or 6 secs a day.
  - Let's take 250 -> 20secs a day
  - Let's assume miner will only sync to some NTP-like server once a week (Windows 10 default) -> 140s.
- buffer: Let's assume you're in a network doing packet inspections and other heavy filtering, may incur another 10s delay (awful case).

so we get `ALLOWABLE_CLOCK_DRIFT = 5 + 140 + 10 = 155s` in the very worst case. Let's call it 150s for cleanliness?

**Comment by pooja** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Question on timestamp comparison in the spec](https://trello.com/c/MAjwwqDQ/15-question-on-timestamp-comparison-in-the-spec)

**Comment by sternhenri** [comment]
FYI, given @jzimmerman's recent work, using a cutoff time on honest miners accepting blocks, we are likely to remove grace period.

In fact we will implement the contrary which is a cutoff time within the period by which time honest miners should no longer accept new blocks, even if valid (in order to avoid people submitting blocks late).

Reasonable numbers are as follows:
- reasonable chronometer has 69PPM skew --> 6 secs skew a day
- However a CPU grade crystal gets us on the order of 1 to E-6 PPM --> or around .6 secs a week ([link](https://www.hindawi.com/journals/jcnc/2008/583162/))
- a miner can be expected to run ntp on the order of once an hour (it's cheap), so we're on the order of 4ms of skew per hour.

Even if you 10x that, skew becomes the last of our concerns compared to network delay.

Looking at [ethstats](https://ethstats.net/), 90% of the network is reached within 2.5 seconds, 95% within 4.75s. 

Therefore, assuming a cutoff of no more than 5 seconds, we should be fine...

Thoughts @whyrusleeping @anorth?

Note that this is still at the idea stage, but a candidate for spec upgrade.

**Comment by anorth** [comment]
I'm 👍 assuming low clock skew.

**Comment by sternhenri** [comment]
closing in favor of https://github.com/filecoin-project/specs/pull/602
