### ISSUE TITLE
Genensis state with storage commitments to bootstrap mining

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#526]
A network must launch with at least one miner actor with storage power, and thus the ability to mine blocks. This goes for numerous test and development networks, as well as "real" ones.

`go-filecoin` at the moment implements a privileged "bootstrap miner" which can fake its sector commitments and PoSts. This involves special cases in actor code and is not a good mechanism for real networks.

This issue is a request for a general mechanism for bootstrapping miner power in the genesis state with a minimum of special. E.g., I would expect all miners to be required to post real PoSts as soon as the network starts.

(The genesis state general and specifics are also generally missing from the spec)

cc @acruikshank @whyrusleeping

**Comment by whyrusleeping** [comment]
Yeah, the way i've been doing this is to craft a somewhat 'fake' state for the initial miner actors,  giving them power, and setting their provingPeriodEnd to something like block 100. It doesnt require any special cases in actor code.

Additionally, 'manually' editing state here means we can skip having correct snark proofs for the commit sector invocations to get sectors actually into the genesis block (otherwise we would have to worry about the randomness input to the sealing process, and then we would have to make the randomness known, which would allow people to predict who will win a block before network launch, and is just messy). That's not to say we shouldnt validate the proofs for sector commitments in the genesis block, but we can use some fixed randomness to do the replication that doesnt have to come from the chain (avoiding more special cases)

**Comment by acruikshank** [comment]
@whyrusleeping this seems pretty clean. Some alternatives/additions:

1. Keep a special-case bootstrap miner code, but eliminate it in a protocol upgrade scheduled soon after start.
2. Use a bootstrap miner (special or not) to startup a primer network. Have some set of miners prove storage on this network. Transfer miner state (sans bootstrap miner) to the new network. We don't store commitSector proofs, so their source of randomness isn't an issue in the new chain. We'll be able to verify the storage in the old chain before transferring the state to new genesis.
3. Do the above with some sort of ceremony instead of a network where miners receive randomness, seal storage and submit commitments and proofs within some period of time for inclusion in genesis. Now that I type it out, the primer network seems like a specific (and perhaps optimal) version of this ceremony.

Seems like initializing miners with fake storage is good enough for most of our ad hoc network needs, though.
