### ISSUE TITLE
Add current time to Random Beacon call in PoSt

### ISSUE THREAD

**Issue by nicola** [filecoin-project/specs#54]
In PoSt we do: `self.beacon.get::<H::Domain>(t);`, where `t` goes from `0` to `POST_PERIODS_COUNT`.

- However, this is technically not correct, and we need to query the beacon at the exact time (hence `t` + `t_commit`)
- Technically the time should be defined as block chain epochs, or at least mapped to it.

This requires a spec change and an implementation change. This could be for now and incremental change, where we first add t_commit and then we do a mapping to the Random Beacon.

**Comment by pooja** [comment]
@nicola What's the status on this issue?

**Comment by whyrusleeping** [comment]
@nicola speaking: 

- Calculate the probability of having multiple running forks (e.g. whats the prob of having 10 forks?)
- Check if provers can wait before picking the block randomness
- Check if we can have exponential set of checks (e.g. one in provingtime/2, one in provingtime3/4..)

We use tickets as the beacon randomness to the PoSt. There might be cases where miners are using in PoSt a non-winning ticket of a block that will be included in the chain. Since we use the ticket as input to the VDF, it shouldnt matter (to be checked) which ticket they pick, as long as the ticket is in a block that is in the longest chain. Note that this trick doesn't work if VDF is broken.

**Comment by whyrusleeping** [comment]
Ideally, we don't have to have miners run a post per potential fork.

**Comment by mishmosh** [comment]
Closing as stale.
