### ISSUE TITLE
codeGen needs explicit CIDs and explicit generic containers

### ISSUE THREAD

**Issue by jbenet** [filecoin-project/specs#562]
@jzimmerman two high priority asks for `.id` from @whyrusleeping:
- (1) Be able to be explicit about CIDs (as in the original ipld schemas)
  - ie. explicitly mark them w/ `&Type` or `*Type`. 
  - without that, it should mean an embedded/inline struct (not a reference). This is because lots of small data structures exist that should not go through the `cid` indirection.
  - implementors need _very explicit_ notation to know the exact shape of the data
- (2) Be able to describe containers that will go on chain explicitly:
  - `Sectors {SectorNum: SectorCommitment}` is bad
  - `Sectors AMT<SectorNum, SectorCommitment>` is good
    - or, if we want the `{}` syntax:`Sectors AMT{SectorNum: SectorCommitment}`
    - or if we want go syntax: `Sectors AMT[SectorNum]SectorCommitment`

Other:
- (2) above can be achieved with or without generics

## In the mean time
- For (1), we'll be explicit by declaring types like this:
    ```
    // inside .id
    type Foo struct {}
    type FooCID ipld.CID
   
    type bar struct {
      fooRef FooCID
    }
    ```
  - Q: @jzimmerman could we do `fooRef Foo_R` instead, since `Foo_R` is effectively this?
    ```
    // inside .id
    type Foo struct {}
    type bar struct {
      fooRef Foo_R
    }
    ```
- For (2), we'll be explicit by declaring types like:
  ```go
  // inside .id
  type AMT_SectorNum_SectorCommitment {SectorNum: SectorCommitment}
  type bar struct {
    mySectorMap AMT_SectorNum_SectorCommitment
  }
  ```

**Comment by jbenet** [comment]
cc @nicola @ZX @sternhenri @porcuquine FYI

**Comment by jzimmerman** [comment]
@jbenet @whyrusleeping  (1) should be doable. For separation of concerns, it may be more natural to represent this via an `@` attribute on the field (e.g., `@inline` or `@indirect`) rather than as a separate type declaration syntax. Also, we can still preserve the type `CID<T>` for when we want to use CIDs directly without dereferencing them.

- Would be helpful to know, based on your experience thus far, which attribute should be the default -- i.e., if struct A has a field of non-primitive type struct B, is it more common for B to be serialized as inline or indirect?

For (2), I'm inclined to defer this until we have generics completed, since otherwise we'll effectively be implementing generics twice (once in this special case, and once in general). Does that seem reasonable? Until then, I think the interim solution (`AMT_SectorNum_SectorCommitment`) sounds good to me.

Re: the question on `_R`: currently the type `Foo_R` is only present at the Go level, and does not exist in the DSL (this is intentional, to avoid exposing the implementation details). My sense is this will continue to be true even after (1) has been completed.
