### ISSUE TITLE
Block rewards and transaction fee visibility on chain

### ISSUE THREAD

**Issue by steven004** [filecoin-project/specs#647]
# Problem to Solve
This is a feature request to solve the following problem: 

*Currently it is very hard to check a miner owner's gain of block reward and transaction fee from the chain since they are not in any messages or blocks. So, when you check your balance history, it does not reflect all the income. It looks miner owner's balance just changes silently*

# Solution approach
A simple way is to add two fields into block header, one is for block reward for this block, another is for transaction fee gained via executing all the messages in the block.

**Comment by anorth** [comment]
#662 specifies implicit messages to be sent to the treasury actor (#665) for the earning of block reward. Implicit means the message won't actually appear on chain, but its structure is clearly defined. Each block can be thought of as having that message as its first message. 

It is impossible to know the transaction fees to be gained for a block in isolation, because they depend on other blocks in the tipset. The fee is not known until the blocks in the next epoch confirm their parent state. Thus we can never make this computable from a single miner's blocks in isolation: you must inspect the state and compute the difference in balance from one epoch to the next.

**Comment by steven004** [comment]
I wanted to figure out one thing from an owner point of view: how could I, as an owner, know exactly when and how my income comes in an easy way. 

From my understanding, if we do not have the explicit visibility of block reward and transaction fee, when I check my account, I could just see, oh, my balance is changed, but how and when, what exactly amount for each round. As an account user, should I go back to re-calculate? 

There should be an easy way, or API to just retrieve it from the chain.

**Comment by anorth** [comment]
I can understand the desire, but a few things make this more difficult for Filecoin than it might be for other chains.
- the block reward is different every epoch (because it decreases smoothly)
- we _could_ put the block reward message on-chain, but the actual reward value would be in a nested send, not transparently on-chain, so you'd still have to execute the message to determine the value
- the gas fees are not calculable until the next epoch, when the other tipset blocks are known

Some piece of higher-level software could work out the attribution of value by replaying the messages, but I don't think it's in scope for our first release.

**Comment by steven004** [comment]
WHY the block reward should be visible on the chain is partly (mostly)
because they are different among every epoch. The block reward is
determined for each epoch when the block is generated, and it could be in
the block and can be verified. We could consider it be in the header.

Regarding the transaction fee is a little different, but if it is not on
chain, it's still hard for users to verify their incomes. Considering it
can be determined in the next epoch. There is another way to show this: to
just put it into the blocks in the next epoch, as we do for parentWeight,
which can also be worked out by replaying the chain.

Agreed that we may not consider this recently. Before that, we will
consider using a database to save related attributes in a DB for the
filecoin explorer, which will provide some level of visibility.
