### ISSUE TITLE
Don't use SendCatchingErrors

### ISSUE THREAD

**Issue by anorth** [filecoin-project/specs#664]
I strongly believe we should not use `SendCatchingErrors` at all, but am willing to relent to its use in the CronActor. Outside of that, I think it's a very bad idea.

This use multiplies the space of chain states that might result from a top-level message, and specifically expands it to include cases where the state of multiple collaborating actors might not be consistent with each other. Analysing all those possibilities is really hard, huge complexity.

Instead, actor methods should be correct (🎉), and not return errors except when the desired semantics cannot be achieved, in which case the whole message execution should abort. If we desire semantics like "try to do X but its ok if you can't" then we should just write a method that does that, and returns a value indicating what it achieved.

Defensive programming like catching opaque errors and attempting to proceed has no place in the world of security-critical, immutable smart contracts. We must understand and exercise every possible state transition, and if something unexpected happens should fall back to making no state transition at all.

**Comment by anorth** [comment]
I would prefer we remove it from CronActor too, if possible.

**Comment by jzimmerman** [comment]
I agree we should only use `SendCatchingErrors` when that's really what we mean (which is quite rare), and otherwise always use `SendPropagatingErrors`. #644 makes this more explicit by giving `SendCatchingErrors` a different return type. However, I don't see how we can avoid it in the case of cron, which must not be halted by failures of some of its sub-dispatches.

> Defensive programming like catching opaque errors and attempting to proceed has no place in the world of security-critical, immutable smart contracts. We must understand and exercise every possible state transition

Emphatically agree. The only point I'd make there is that falling back to making no state transition at all might (in rare cases) not be the safest course of action.

> If we desire semantics like "try to do X but its ok if you can't" then we should just write a method that does that, and returns a value indicating what it achieved.

I think this is ultimately a language design question. In languages that provide automated error return value propagation (e.g., Rust's error-handling macros), this is clearly preferable to exceptions/panics. However, in order to use error return values in Go, currently we must manually check and propagate the error cases, or risk failing silently. In this environment, I believe exceptions/panics may actually be safer, provided we understand the precise semantics we are trying to achieve, and that when we catch errors we do so with specific intent to simulate error return values, rather than as a means of general "defensive programming".

**Comment by anorth** [comment]
In the case of cron, we can remove it by assuring ourselves that the methods it calls never fail (if the state is valid). We write all the methods, remember. We can add bells and whistles for user-provided contracts when that happens.

**Comment by jzimmerman** [comment]
Agreed, but it will still be a security challenge to enforce that those methods never fail, even under arbitrary adversarial message input. I don't think we should make that challenge harder for ourselves by allowing failures to cascade.
