### ISSUE TITLE
state machine spec: decide & doc whether nonce is needed only for account actors

### ISSUE THREAD

**Issue by shannonwells** [filecoin-project/specs#78]
>“(TODO: the nonce is really only needed for external user interface actors, AKA account actors. Maybe we should find a way to clean that up?)”

**Comment by pooja** [comment]
Probably nonces only on account actors. Should discuss.

**Comment by dignifiedquire** [comment]
Question: Is it worth complicating the send logic to differentiate between account actors and others in such a way?

**Comment by whyrusleeping** [comment]
I really like this idea, especially because of the direction it pushes us in. This would mean moving the nonce from the Actor object into the AccountActor state, which also means we should move the nonce from being a top level field on the Message type to being a parameter of the call. In order for it to be a call parameter, we need to have 'sending a message *from* the account actor' actually be a message to the account actor requesting it make a call on another actor. So a message to call 'CommitSector' on a miner actor would look like:

```
To: MyAccountActor,
Method: "Invoke",
Params: [
  nextNonce=5,
  targetActor="MyMinerActor",
  parameters= [ commit sector parameters ]
]
```

This would also make it make sense to put the messages signature in a place where logic on the account actor could validate it.

This would be a pretty significant change, and the effect on end users would be mostly more complicated message creation logic. So I think we should probably not do this one right now...

**Comment by pooja** [comment]
Needs to be discussed with dev.

**Comment by pooja** [comment]
@anorth Would be good to get your thoughts on this issue as well.

**Comment by anorth** [comment]
I don't forsee any major issues. I agree with the desire to do so and also not to do it *right now*. Since it's a real simplification I think we should strongly consider doing it before we declare the protocol testnet-ready, but we may decide to postpone it again at that point.

I think it's more or less just a matter of coding.

**Comment by pooja** [comment]
@anorth Is there a place in the go-filecoin priorities for priorities pending review? We can maybe add this one to that list and then decide where it should fall at some later point

**Comment by anorth** [comment]
I'll make a note internally. I hope to work on on opening up our roadmap in
the near future.

**Comment by pooja** [comment]
Sounds great!

**Comment by dignifiedquire** [comment]
We (@whyrusleeping & me) like it, but agree that this is too complex to add for now.

**Comment by pooja** [comment]
Should we leave this open for now then, but mark it p3?

**Comment by dignifiedquire** [comment]
I don't think so, we have enough things here, and can reopen it when we are running out of things to do :D
