### ISSUE TITLE
Genesis block should be height 1

### ISSUE THREAD

**Issue by magik6k** [filecoin-project/specs#874]
Some actors use -1 as a constant for 'undefined epoch', which is really bugging me as it's not a zero-value, which can lead to all sorts of bugs (and is generally annoying - adds yet another thing to the list of 'do we initialize this variable correctly?').

Reserving epoch 0 as 'undefined epoch' and having the genesis be height 1 makes this a bit cleaner IMO.

**Comment by sternhenri** [comment]
I think I am responsible for this as it made sense to me to have `ChainHeight` be 0-indexed. With that said, if you, @anorth or @whyrusleeping have issues with it, I can work to change it...

**Comment by anorth** [comment]
One way in which genesis epoch = 1 would make sense is that we could then provide epoch = 0 for computing the genesis state (i.e. the state that the genesis block points to), and then 1 for evaluation of the messages in the genesis block.

Otherwise we have to use -1 for the pre-genesis state, so shouldn't use that for an "invalid" sentinel.

cc @ZenGround0
